apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikasclaim
  namespace: vikasns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: fast
