apiVersion: v1
kind: Pod
metadata:
  name: mypodvikas
  namespace: vikasns
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html/"
        name: myspace
  volumes:
    - name: myspace
      persistentVolumeClaim:
        claimName: vikasclaim 
